export const vpoCelloSoloSustainSamples = [
  { rootNote: 42, url: new URL('./samples/vpo/cello-solo-sustain/2_Gb-PB-loop.wav', import.meta.url).href },
  { rootNote: 45, url: new URL('./samples/vpo/cello-solo-sustain/2_A-PB-loop.wav', import.meta.url).href },
  { rootNote: 49, url: new URL('./samples/vpo/cello-solo-sustain/3_Db-PB-loop.wav', import.meta.url).href },
  { rootNote: 53, url: new URL('./samples/vpo/cello-solo-sustain/3_F-PB-loop.wav', import.meta.url).href },
  { rootNote: 57, url: new URL('./samples/vpo/cello-solo-sustain/3_A-PB-loop.wav', import.meta.url).href },
  { rootNote: 60, url: new URL('./samples/vpo/cello-solo-sustain/4_C-PB-loop.wav', import.meta.url).href },
  { rootNote: 63, url: new URL('./samples/vpo/cello-solo-sustain/4_Eb-PB-loop.wav', import.meta.url).href },
  { rootNote: 67, url: new URL('./samples/vpo/cello-solo-sustain/4_G-PB.wav', import.meta.url).href },
  { rootNote: 70, url: new URL('./samples/vpo/cello-solo-sustain/4_Bb-PB.wav', import.meta.url).href },
];

export const vpoFluteSoloSustainSamples = [
  { rootNote: 69, url: new URL('./samples/vpo/flute-solo-sustain/LDFlute_susvib_A3_v1_1-PB-loop.wav', import.meta.url).href },
  { rootNote: 81, url: new URL('./samples/vpo/flute-solo-sustain/LDFlute_susvib_A4_v1_1-PB-loop.wav', import.meta.url).href },
  { rootNote: 93, url: new URL('./samples/vpo/flute-solo-sustain/LDFlute_susvib_A5_v1_1-PB-loop.wav', import.meta.url).href },
  { rootNote: 60, url: new URL('./samples/vpo/flute-solo-sustain/LDFlute_susvib_C3-PB-loop.wav', import.meta.url).href },
  { rootNote: 72, url: new URL('./samples/vpo/flute-solo-sustain/LDFlute_susvib_C4_v1_2-PB-loop.wav', import.meta.url).href },
  { rootNote: 84, url: new URL('./samples/vpo/flute-solo-sustain/LDFlute_susvib_C5_v1_1-PB-loop.wav', import.meta.url).href },
  { rootNote: 96, url: new URL('./samples/vpo/flute-solo-sustain/LDFlute_susvib_C6_v1_1-PB-loop.wav', import.meta.url).href },
  { rootNote: 64, url: new URL('./samples/vpo/flute-solo-sustain/LDFlute_susvib_E3-PB-loop.wav', import.meta.url).href },
  { rootNote: 76, url: new URL('./samples/vpo/flute-solo-sustain/LDFlute_susvib_E4_v1_2-PB-loop.wav', import.meta.url).href },
  { rootNote: 88, url: new URL('./samples/vpo/flute-solo-sustain/LDFlute_susvib_E5_v1_2-PB-loop.wav', import.meta.url).href },
];

export const vpoViolinSoloSustainSamples = [
  { rootNote: 55, url: new URL('./samples/vpo/violin-solo-sustain/3_G-PB-loop.wav', import.meta.url).href },
  { rootNote: 56, url: new URL('./samples/vpo/violin-solo-sustain/3_Ab-PB-loop.wav', import.meta.url).href },
  { rootNote: 57, url: new URL('./samples/vpo/violin-solo-sustain/3_A-PB-loop.wav', import.meta.url).href },
  { rootNote: 59, url: new URL('./samples/vpo/violin-solo-sustain/3_B-PB-loop.wav', import.meta.url).href },
  { rootNote: 60, url: new URL('./samples/vpo/violin-solo-sustain/4_C-PB.wav', import.meta.url).href },
  { rootNote: 61, url: new URL('./samples/vpo/violin-solo-sustain/4_Db-PB.wav', import.meta.url).href },
  { rootNote: 62, url: new URL('./samples/vpo/violin-solo-sustain/4_D-PB.wav', import.meta.url).href },
  { rootNote: 63, url: new URL('./samples/vpo/violin-solo-sustain/4_Eb-PB.wav', import.meta.url).href },
  { rootNote: 65, url: new URL('./samples/vpo/violin-solo-sustain/4_F-PB.wav', import.meta.url).href },
  { rootNote: 66, url: new URL('./samples/vpo/violin-solo-sustain/4_Gb-PB.wav', import.meta.url).href },
  { rootNote: 67, url: new URL('./samples/vpo/violin-solo-sustain/4_G-PB.wav', import.meta.url).href },
  { rootNote: 68, url: new URL('./samples/vpo/violin-solo-sustain/4_Ab-PB.wav', import.meta.url).href },
  { rootNote: 69, url: new URL('./samples/vpo/violin-solo-sustain/4_A-PB.wav', import.meta.url).href },
  { rootNote: 72, url: new URL('./samples/vpo/violin-solo-sustain/5_C-PB.wav', import.meta.url).href },
  { rootNote: 73, url: new URL('./samples/vpo/violin-solo-sustain/5_Db-PB.wav', import.meta.url).href },
  { rootNote: 74, url: new URL('./samples/vpo/violin-solo-sustain/5_D-PB.wav', import.meta.url).href },
  { rootNote: 75, url: new URL('./samples/vpo/violin-solo-sustain/5_Eb-PB.wav', import.meta.url).href },
  { rootNote: 76, url: new URL('./samples/vpo/violin-solo-sustain/5_E-PB.wav', import.meta.url).href },
  { rootNote: 77, url: new URL('./samples/vpo/violin-solo-sustain/5_F-PB.wav', import.meta.url).href },
  { rootNote: 78, url: new URL('./samples/vpo/violin-solo-sustain/5_Gb-PB.wav', import.meta.url).href },
  { rootNote: 79, url: new URL('./samples/vpo/violin-solo-sustain/5_G-PB.wav', import.meta.url).href },
  { rootNote: 80, url: new URL('./samples/vpo/violin-solo-sustain/5_Ab-PB.wav', import.meta.url).href },
  { rootNote: 82, url: new URL('./samples/vpo/violin-solo-sustain/5_Bb-PB.wav', import.meta.url).href },
  { rootNote: 83, url: new URL('./samples/vpo/violin-solo-sustain/5_B-PB.wav', import.meta.url).href },
  { rootNote: 84, url: new URL('./samples/vpo/violin-solo-sustain/6_C-PB.wav', import.meta.url).href },
  { rootNote: 85, url: new URL('./samples/vpo/violin-solo-sustain/6_Db-PB.wav', import.meta.url).href },
  { rootNote: 86, url: new URL('./samples/vpo/violin-solo-sustain/6_D-PB.wav', import.meta.url).href },
  { rootNote: 90, url: new URL('./samples/vpo/violin-solo-sustain/6_Gb-PB.wav', import.meta.url).href },
  { rootNote: 92, url: new URL('./samples/vpo/violin-solo-sustain/6_Ab-PB.wav', import.meta.url).href },
  { rootNote: 94, url: new URL('./samples/vpo/violin-solo-sustain/6_Bb-PB-loop.wav', import.meta.url).href },
];

export const vpoBassSoloSustainSamples = [
  { rootNote: 45, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_A1_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 59, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_B2_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 49, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_Csharp2_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 36, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_C1_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 38, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_D1_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 40, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_E1_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 52, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_E2_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 30, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_Fsharp0_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 42, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_Fsharp1_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 44, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_Gsharp1_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 56, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_Gsharp2_v3_rr1-PB-loop.wav', import.meta.url).href },
  { rootNote: 31, url: new URL('./samples/vpo/bass-solo-sustain/BKCtbss_SusVib_G0_v3_rr1-PB-loop.wav', import.meta.url).href },
];
